<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Default test"
           tests="9"
           failures="3"
           errors="0"
           skipped="0"
           time="677.708">
  <properties />
            <testcase name="TC092DbCUN_18" time="105.690" classname="com.dts.adminportal.dts.test.DTSUser092DCreateUser">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:496)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  com.dts.adminportal.dts.test.DTSUser092DCreateUser.TC092DbCUN_18(DTSUser092DCreateUser.java:640)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
  org.testng.TestNG.run(TestNG.java:1024)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
      </failure>

          </testcase>
            <testcase name="TC092DbCUN_01" time="42.629" classname="com.dts.adminportal.dts.test.DTSUser092DCreateUser">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:496)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  com.dts.adminportal.dts.test.DTSUser092DCreateUser.TC092DbCUN_01(DTSUser092DCreateUser.java:359)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
  org.testng.TestNG.run(TestNG.java:1024)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
      </failure>

          </testcase>
            <testcase name="TC092DbCUN_11" time="88.057" classname="com.dts.adminportal.dts.test.DTSUser092DCreateUser">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:496)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  com.dts.adminportal.dts.test.DTSUser092DCreateUser.TC092DbCUN_11(DTSUser092DCreateUser.java:476)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
  org.testng.TestNG.run(TestNG.java:1024)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC092DaCUB_10" time="41.020" classname="com.dts.adminportal.dts.test.DTSUser092DCreateUser" />
                <testcase name="TC092DaCUB_01" time="65.328" classname="com.dts.adminportal.dts.test.DTSUser092DCreateUser" />
                <testcase name="TC092DaCUB_13" time="115.177" classname="com.dts.adminportal.dts.test.DTSUser092DCreateUser" />
                <testcase name="TC092DaCUB_06" time="51.264" classname="com.dts.adminportal.dts.test.DTSUser092DCreateUser" />
                <testcase name="TC092DaCUB_16" time="134.985" classname="com.dts.adminportal.dts.test.DTSUser092DCreateUser" />
                <testcase name="TC092DaCUB_04" time="33.558" classname="com.dts.adminportal.dts.test.DTSUser092DCreateUser" />
      
</testsuite>
